rule test:
    input:
        # define input paths
        fastq='/input/trimmmed_repaired_R1.fastq.gz'
    threads : 8
    output:
        mapping= '/output/whitelist.csv'
    benchmark : '/output/ benchmark.txt'
    script: 'scripts/top_barcodes.py'
