SAMPLES=["252_S1","253_S2","254_S3","255_S4"]

rule all:
  input: ["/output/{sample}/Aligned.merged.bam".format(sample=sample) for sample in SAMPLES]



rule test:
    input:
        mapped='/input/{sample}/Aligned.out.bam',
        R1_ref = '/input/{sample}/trimmmed_repaired_R1.fastq.gz'
    output: '/output/{sample}/Aligned.merged.bam'
    params:
        cell_barcode_length=12,
        umi_barcode_length=8,
        discard_secondary_alignements=True
    benchmark: '{output}/benchmark.{sample}.txt'
    conda: 'envs/merge_bam.yaml'
    script: 'scripts/merge_bam.py'