rule test:
    input:
        # define input paths
        refflat='/input/annotation/curated_annotation.refFlat',
            inbam='/input/Aligned.repaired.bam',
        correctbam='/input/gene_exon_tagged.bam'
    output:
        # define output path
        out='log.txt'
    conda: 'envs/tag_read_with_gene_exon.yaml'
    benchmark : 'benchmark.txt'
    script: 'scripts/test.py'
