rule test:
    input:
        # define input paths
        refflat='annotation.refFlat',
        inbam='in.bam'
        correctbam='correct.bam'
    output:
        # define output path
        outbam='out.bam'
    conda: 'envs/tag_read_with_gene_exon.yaml'
    script: 'scripts/test.py'
